<a href="https://colab.research.google.com/github/rohan260696/CE888-LAB-Solutions-/blob/master/CE888-LAB-Solutions-/Lab1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# CE888 DATA SCIENCE AND DECISION MAKING 
##LAB 1 Solutions 

1. Create a (4 x 2) integer array and print it's attributes

In [0]:
array = [[2,3],[3,5],[6,7],[9, 10]]

In [7]:
array

[[2, 3], [3, 5], [6, 7], [9, 10]]

2. create an array of dimension (1,10) and sort it in ascending and descending order

In [0]:
arr2 = []
for i in range (0,10):
  arr2.append(i)

In [70]:
arr2 
# ascending order

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [0]:
arr2.sort(reverse = True) 

In [74]:
arr2
# descending order 

[9, 8, 7, 6, 5, 4, 3, 2, 1, 0]

3. Convert an 1D array [1 2 3 4 5 6 7 8 9] to 2D array [[1 2 3], [4 5 6], [7 8 9]]


In [0]:
import numpy as np
arr3 = [1,2,3,4,5,6,7,8,9]
arr3_2D = np.reshape(arr3,(-1,3))

In [34]:
arr3_2D

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

4.Stack two arrays of any size horizontally and vertically

In [0]:
arr4 = []
arr5 = []
for i in range (0,4):
  arr4.append(i)
for j in range (5,9):
  arr5.append(j)

In [51]:
print (arr4)
print (arr5)
horizontalStack = np.stack((arr4,arr5),axis = 0)
print("horizontal: \n", horizontalStack)
verticalStack = np.stack((arr4,arr5),axis = 1)
print("vertical: \n", verticalStack)

[0, 1, 2, 3]
[5, 6, 7, 8]
horizontal: 
 [[0 1 2 3]
 [5 6 7 8]]
vertical: 
 [[0 5]
 [1 6]
 [2 7]
 [3 8]]


5.Create two array of same size and find common elements

In [0]:
arr6 = []
arr7 = []
for i in range (0,5):
  arr6.append(i)
for j in range (3,8):
  arr7.append(j)

In [56]:
print(arr6)
print(arr7)
print ("common elements are: ", np.intersect1d(arr6,arr7))

[0, 1, 2, 3, 4]
[3, 4, 5, 6, 7]
common elements are:  [3 4]


6. Create a 2D array of 5 by 5 and find the min and max values from each row and each column

In [67]:
arr8 = np.random.random((5,5))
arr8

array([[0.59028617, 0.77378827, 0.27219046, 0.33171157, 0.75794472],
       [0.47386794, 0.24421162, 0.98842243, 0.79030143, 0.43561304],
       [0.54227464, 0.20182842, 0.66804983, 0.22641286, 0.00304085],
       [0.22100691, 0.45938514, 0.09385601, 0.28140292, 0.28822723],
       [0.90552994, 0.43258182, 0.38166953, 0.3111311 , 0.89635289]])

In [68]:
print("max:", arr8.max())
print("min:", arr8.min())

max: 0.9884224295793863
min: 0.003040852161128038


7.Create an array of size 100 and compute the mean, median, standard deviation.

In [78]:
arr9 = np.random.random((100))
arr9

array([9.47641898e-04, 4.68082959e-01, 2.05465387e-01, 8.49293840e-01,
       9.25129780e-01, 6.41569975e-01, 6.25656723e-01, 2.63578950e-01,
       3.89370287e-01, 6.36801760e-01, 9.18547247e-02, 5.58009435e-01,
       6.88037655e-01, 5.81225151e-01, 4.07857286e-01, 1.59044810e-01,
       7.48281869e-01, 4.11961726e-01, 4.51953973e-01, 5.36874594e-01,
       6.05207913e-01, 2.01182161e-01, 7.81208255e-01, 5.65680787e-01,
       3.02272175e-01, 7.79653566e-01, 9.10095248e-01, 2.71004880e-01,
       5.24344358e-01, 7.02725289e-02, 3.00407115e-01, 8.19883751e-01,
       9.61243100e-01, 4.59375402e-01, 8.32503987e-01, 8.65777144e-01,
       2.66078737e-01, 3.95407714e-01, 3.74053088e-01, 7.07944356e-01,
       8.42331530e-01, 9.27724643e-01, 8.36458029e-01, 7.16909688e-01,
       2.90128239e-01, 7.76352051e-01, 3.73664114e-01, 8.75092318e-01,
       7.75090569e-02, 2.52635832e-01, 2.40630942e-01, 3.64800941e-01,
       7.11345479e-01, 4.45591396e-01, 9.09818048e-01, 7.99743273e-01,
      

In [84]:
from statistics import median

print("mean:",arr9.mean())
print("median:",median(arr9))
print("std dev:",arr9.std())

mean: 0.5203741194019874
median: 0.5116582313005773
std dev: 0.26988823259185263


8. Normalize a 5x5 random matrix

In [88]:
arr9 = np.random.random((5,5))
arr9

array([[0.71903059, 0.63722391, 0.24937038, 0.31680087, 0.2491582 ],
       [0.87555124, 0.53012821, 0.08835389, 0.8498927 , 0.20248337],
       [0.7021651 , 0.67184912, 0.11731262, 0.60944631, 0.69084837],
       [0.90415842, 0.45745798, 0.08450757, 0.74986284, 0.92600475],
       [0.28530621, 0.8907958 , 0.78636918, 0.59806139, 0.5352944 ]])

In [134]:
from sklearn.preprocessing import normalize
normalize(arr9)

array([[0.67117465, 0.59481271, 0.23277324, 0.2957158 , 0.23257518],
       [0.64922485, 0.39309225, 0.06551478, 0.63019893, 0.15014225],
       [0.52236625, 0.49981309, 0.08727314, 0.45338936, 0.51394733],
       [0.57721101, 0.29203929, 0.05394928, 0.47870935, 0.59115762],
       [0.19514484, 0.60928993, 0.53786381, 0.40906433, 0.36613272]])


9. Consider an array of dimension (4,4,3), how to mulitply it by an array with dimensions (4,4)?



In [0]:
arr10 = np.random.random((4,4,3))
arr11 = np.random.random((4,4))

In [152]:
arr10

array([[[1.96751652e-01, 1.07524078e-02, 2.63172251e-01],
        [6.42860616e-02, 1.49077469e-01, 9.76367200e-01],
        [9.26592224e-01, 6.30466564e-01, 4.31444289e-01],
        [4.32574320e-01, 2.49433541e-01, 5.76660110e-01]],

       [[5.68977596e-01, 1.44753899e-01, 1.05819957e-01],
        [6.92206157e-01, 6.41165581e-01, 8.09066519e-01],
        [3.32084643e-01, 6.79170939e-01, 9.53358294e-01],
        [8.20468400e-01, 8.03445985e-01, 3.96978610e-01]],

       [[2.03516285e-01, 3.15583369e-01, 7.93772960e-01],
        [8.73318163e-04, 2.58998869e-01, 4.16114888e-01],
        [5.43647234e-01, 5.35827986e-01, 2.41893201e-02],
        [9.05507250e-01, 7.62510649e-01, 7.39308088e-01]],

       [[9.30603173e-01, 1.37430765e-01, 4.47175218e-01],
        [1.64552238e-01, 2.55011533e-01, 7.84308619e-01],
        [9.79311980e-01, 6.15241733e-01, 5.85516845e-01],
        [5.86539658e-01, 2.48795626e-01, 8.89327650e-02]]])

In [153]:
arr11

array([[0.05871539, 0.58915101, 0.45397266, 0.60246558],
       [0.05564242, 0.15301207, 0.79739441, 0.15331888],
       [0.65270584, 0.70119129, 0.97201816, 0.8344655 ],
       [0.27210435, 0.18395406, 0.93986176, 0.877167  ]])

In [174]:
arr10 * arr11[:,:,None]

array([[[1.15523509e-02, 6.31331866e-04, 1.54522626e-02],
        [3.78741979e-02, 8.78291411e-02, 5.75227719e-01],
        [4.20647541e-01, 2.86214586e-01, 1.95863913e-01],
        [2.60611140e-01, 1.50275124e-01, 3.47417870e-01]],

       [[3.16592891e-02, 8.05445693e-03, 5.88807827e-03],
        [1.05915900e-01, 9.81060759e-02, 1.23796947e-01],
        [2.64802438e-01, 5.41567111e-01, 7.60202575e-01],
        [1.25793292e-01, 1.23183435e-01, 6.08643140e-02]],

       [[1.32836268e-01, 2.05983108e-01, 5.18100247e-01],
        [6.12363089e-04, 1.81607751e-01, 2.91776135e-01],
        [5.28434982e-01, 5.20834531e-01, 2.35124583e-02],
        [7.55614556e-01, 6.36288827e-01, 6.16927090e-01]],

       [[2.53221172e-01, 3.73955090e-02, 1.21678322e-01],
        [3.02700529e-02, 4.69104079e-02, 1.44276758e-01],
        [9.20417877e-01, 5.78242175e-01, 5.50304890e-01],
        [5.14493233e-01, 2.18235313e-01, 7.80088867e-02]]])